### PR TITLE
dominoes: Check that last can match first; Check that output dominoes = input dominoes

### LINKED ISSUE #139: dominoes tests too lenient, Some [(1, 2)] passes every test that expects Some
The function that unconditionally returns `Some [(1, 2)]` passes 7/12 tests (all of them that expect a Some); the only tests that fail are those tests that are expecting a `None`

This implies that two properties aren't being checked:

1. The front and back of the chain match
2. The dominoes in the solution are the same as the dominoes in the input.

### PR DESCRIPTION
**Pull request by petertseng**
Closes #139 

More detail in individual commit messages.

Sidebar: It could be the case that only the last commit is necessary - is there an input and output pair for which the consecutive-dominoes check and same-dominoes check hold, but the dominoes-at-ends check doesn't hold? Can't think of one. Nevertheless, I include the commit for completeness.

### CODE REVIEW

File: exercises/dominoes/test.ml [hunk 1]
```diff
@@ -4,24 +4,30 @@ open Dominoes
...
 let drop_1_right xs = List.rev xs |> List.tl_exn |> List.rev
 
-let check_chain (chained: dominoe list) = 
+let rotate (x, y) = if x > y then (y, x) else (x, y)
+let norm l = List.map ~f:rotate l |> List.sort ~cmp:compare
+
+let check_chain (input: dominoe list) (chained: dominoe list) =
   let assert_dominoes_match d1 d2 =
     if snd d1 <> fst d2 then failwith @@ sprintf "%s and %s cannot be chained together" (print_dominoe d1) (print_dominoe d2) else () in
   let consecutives = List.zip_exn (drop_1_right chained) (List.tl_exn chained) in
```
Comment (petertseng) [inline exercises/dominoes/test.ml]: or maybe I can change this to `List.zip_exn chained (List.tl_exn chained ++ [List.hd_exn chained])`, so that the list of consecutives will include `(List.last_exn chained, List.hd_exn chained)`

Comment (petertseng) [inline exercises/dominoes/test.ml]: decided I might as well do that.

**Comment by stevejb71** [comment]
These changes make sense.

**Comment by petertseng** [comment]
Oops, I should have updated the template as well, sorry for making you have to do it in #141! I'll leave this as a reminder for myself for next time.

**Comment by stevejb71** [comment]
That's cool. It was only a couple of minutes' work to fix up.
